<?php
/**
 * @file
 * Hooks implementations.
 */

/**
 * Implements hook_help().
 */
function geocoder_autocomplete_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the prova module.
    case 'help.page.geocoder_autocomplete':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Geographic reference autocomplete') . '</p>';
      $output .= '<p>' . t('Data cames from Google services') . '</p>';
      return $output;

    default:
  }
}

/**
 * Form element validate handler for geocoder_autocomplete widget element.
 */
function geocoder_autocomplete_validate($element, \Drupal\Core\Form\FormStateInterface $form_state) {
  if ($geocoded_address = $element['#value']) {
    $geocoded_address_cleaned = trim($geocoded_address, '"');
    $form_state->setValueForElement($element, $geocoded_address_cleaned);
  }
}
